"""PostgreSQL compatibility tests.

The runtime tests need no database server: every statement the app issues is
translated to its PostgreSQL form and parsed with the real PostgreSQL parser
from ``pglast``. Install it with ``pip install pglast`` to enable them; without
it those tests are skipped and the rest of the suite still runs.
"""

import os
import tempfile
import unittest
from unittest.mock import patch

os.environ["ATTENDANCE_MASTER_KEY"] = "test-master-key"
os.environ["ATTENDANCE_DATA"] = tempfile.mkdtemp(prefix="attendance-pg-tests-")
os.environ["ATTENDANCE_DB"] = os.path.join(os.environ["ATTENDANCE_DATA"], "test.db")
os.environ.pop("DATABASE_URL", None)

try:
    from pglast import parse_sql
except ImportError:
    parse_sql = None

from backend import attendance, database as db
from backend.security import encrypt_text
from backend.store import store

PG_URL = "postgresql://user:pass@localhost:5432/attendance"


def parse_as_postgres(sql):
    if parse_sql is None:
        raise unittest.SkipTest("pglast is not installed")
    parse_sql(db._rewrite_placeholders(sql, lambda index: f"${index}"))


class PlaceholderTranslationTests(unittest.TestCase):
    def test_bare_placeholder_is_converted(self):
        self.assertEqual(db._translate_placeholders("SELECT * FROM t WHERE a = ?"), "SELECT * FROM t WHERE a = %s")

    def test_multiple_placeholders_are_converted(self):
        self.assertEqual(
            db._translate_placeholders("SELECT * FROM t WHERE a = ? AND b = ?"),
            "SELECT * FROM t WHERE a = %s AND b = %s",
        )

    def test_question_mark_inside_string_literal_is_kept(self):
        sql = "SELECT * FROM t WHERE a = ? AND b = 'who? me'"
        self.assertEqual(
            db._translate_placeholders(sql),
            "SELECT * FROM t WHERE a = %s AND b = 'who? me'",
        )

    def test_escaped_quote_inside_literal_is_handled(self):
        sql = "SELECT * FROM t WHERE a = 'it''s here?' AND b = ?"
        self.assertEqual(
            db._translate_placeholders(sql),
            "SELECT * FROM t WHERE a = 'it''s here?' AND b = %s",
        )

    def test_question_mark_inside_quoted_identifier_is_kept(self):
        sql = 'SELECT "we?ird" FROM t WHERE a = ?'
        self.assertEqual(db._translate_placeholders(sql), 'SELECT "we?ird" FROM t WHERE a = %s')

    def test_question_mark_inside_line_comment_is_kept(self):
        sql = "SELECT * FROM t -- really? yes\nWHERE a = ?"
        self.assertEqual(
            db._translate_placeholders(sql),
            "SELECT * FROM t -- really? yes\nWHERE a = %s",
        )

    def test_question_mark_inside_block_comment_is_kept(self):
        sql = "SELECT * /* what? */ FROM t WHERE a = ?"
        self.assertEqual(
            db._translate_placeholders(sql),
            "SELECT * /* what? */ FROM t WHERE a = %s",
        )

    def test_generated_update_set_list_translates(self):
        sql = "UPDATE employees SET name = ?, role = ? WHERE id = ?"
        self.assertEqual(
            db._translate_placeholders(sql),
            "UPDATE employees SET name = %s, role = %s WHERE id = %s",
        )


class RecordingConnection:
    """Runs each statement on SQLite after asserting the PostgreSQL form parses."""

    def __init__(self, conn, seen):
        self._conn = conn
        self._seen = seen

    def execute(self, sql, params=()):
        translated = db._translate_placeholders(sql)
        self._seen.append(translated)
        parse_as_postgres(sql)
        return self._conn.execute(sql, params)

    def __getattr__(self, name):
        return getattr(self._conn, name)

    def __enter__(self):
        self._conn.__enter__()
        return self

    def __exit__(self, *exc):
        return self._conn.__exit__(*exc)


@unittest.skipUnless(parse_sql is not None, "pglast is not installed")
class PostgresDialectTests(unittest.TestCase):
    def setUp(self):
        db.init_db()
        with db.get_conn() as conn:
            conn.execute("DELETE FROM attendance")
            conn.execute("DELETE FROM employees")

    def test_postgres_schema_parses(self):
        with patch.object(db, "DATABASE_URL", PG_URL):
            statements = db._schema()
        self.assertTrue(statements)
        for statement in statements:
            parse_as_postgres(db._translate_placeholders(statement))

    def test_postgres_schema_uses_identity_not_autoincrement(self):
        with patch.object(db, "DATABASE_URL", PG_URL):
            joined = " ".join(db._schema())
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", joined)
        self.assertNotIn("AUTOINCREMENT", joined)

    def test_every_runtime_query_is_valid_postgres(self):
        seen = []
        real_get_conn = db.get_conn

        def recording_get_conn():
            return RecordingConnection(real_get_conn(), seen)

        with patch.object(db, "get_conn", recording_get_conn):
            self._exercise_every_query()

        self.assertGreater(len(seen), 20, "expected the full query surface to be exercised")
        joins = [sql for sql in seen if "JOIN" in sql]
        self.assertEqual(len(joins), 4, "the four attendance/employee joins must be validated")

    def _exercise_every_query(self):
        employee = {
            "id": "EMP001",
            "name": encrypt_text("Asha Rao"),
            "department": encrypt_text("Operations"),
            "role": encrypt_text("Engineer"),
            "email": encrypt_text("asha@example.com"),
            "phone": encrypt_text("123"),
            "is_active": 1,
            "created_at": encrypt_text("08:00:00"),
        }
        store.insert_employee(employee)
        store.next_employee_id()
        store.employees()
        store.get_employee("EMP001")
        store.get_active_employee("EMP001")
        store.max_face_label()
        store.set_face_label("EMP001", 1)
        store.set_face_available("EMP001", 1)
        store.get_employee_by_face_label(1)
        store.active_face_labels()
        store.departments()
        store.departments(active_only=True)
        store.count_active_employees()
        store.update_employee("EMP001", {"role": encrypt_text("Senior Engineer")})

        record = {
            "employee_id": "EMP001",
            "date": "2026-09-25",
            "check_in": encrypt_text("09:00:00"),
            "check_out": None,
            "hours": 0,
            "status": "Present",
            "source": "face",
            "created_at": encrypt_text("09:00:00"),
        }
        store.insert_attendance(record)
        row = store.attendance_for("EMP001", "2026-09-25")
        store.attendance_entry("EMP001", "2026-09-25")
        store.attendance_by_date("2026-09-25")
        store.attendance_by_employee("EMP001", 60)
        store.attendance_date_rows("2026-09-25")
        store.attendance_all(5000)
        store.close_attendance(row["id"], encrypt_text("17:00:00"), 8.0)
        store.delete_employee("EMP001")

    def test_checkout_flow_runs_and_validates(self):
        attendance.reset_buffer()
        employee = {
            "id": "EMP010",
            "name": encrypt_text("Bo Li"),
            "department": encrypt_text("Ops"),
            "role": encrypt_text("Lead"),
            "email": encrypt_text("bo@example.com"),
            "phone": encrypt_text("456"),
            "category": "office",
            "is_active": 1,
            "created_at": encrypt_text("08:00:00"),
        }
        store.insert_employee(employee)
        with patch.object(db, "today_str", return_value="2026-09-25"), patch.object(
            db, "now_str", side_effect=["09:00:00", "17:00:00"]
        ):
            first = attendance.record_scan("EMP010")
            final = attendance.record_scan("EMP010")
        self.assertEqual(first["action"], "CHECK-IN")
        self.assertEqual(final["action"], "CHECK-OUT")
        with db.get_conn() as conn:
            conn.execute("DELETE FROM attendance")
            conn.execute("DELETE FROM employees")


class FakeCursor:
    def __init__(self, conn):
        self._conn = conn
        self._rows = []

    def execute(self, sql, params=()):
        self._conn.executed.append((sql, params))
        self._rows = self._conn.rows

    def fetchone(self):
        return self._rows[0] if self._rows else None

    def fetchall(self):
        return list(self._rows)


class FakeRawConnection:
    def __init__(self, rows=()):
        self.executed = []
        self.rows = list(rows)
        self.commits = 0
        self.rollbacks = 0
        self.closed = False

    def cursor(self, row_factory=None):
        return FakeCursor(self)

    def commit(self):
        self.commits += 1

    def rollback(self):
        self.rollbacks += 1

    def close(self):
        self.closed = True


class FakePool:
    def __init__(self):
        self.returned = []
        self.opened = 0

    def getconn(self):
        self.opened += 1
        return FakeRawConnection(rows=[{"id": "EMP001"}])

    def putconn(self, conn):
        self.returned.append(conn)


class PostgresConnectionTests(unittest.TestCase):
    def test_execute_translates_placeholders_and_passes_params(self):
        raw = FakeRawConnection()
        conn = db.PostgresConnection(raw)
        conn.execute("SELECT * FROM employees WHERE id = ?", ("EMP001",))
        sql, params = raw.executed[0]
        self.assertEqual(sql, "SELECT * FROM employees WHERE id = %s")
        self.assertEqual(params, ("EMP001",))

    def test_execute_defaults_to_empty_params(self):
        raw = FakeRawConnection()
        db.PostgresConnection(raw).execute("SELECT 1")
        self.assertEqual(raw.executed[0][1], ())

    def test_fetchone_returns_mapping(self):
        raw = FakeRawConnection(rows=[{"id": "EMP001"}])
        row = db.PostgresConnection(raw).execute("SELECT id FROM employees").fetchone()
        self.assertEqual(row["id"], "EMP001")

    def test_fetchall_returns_empty_list(self):
        raw = FakeRawConnection(rows=[])
        self.assertEqual(db.PostgresConnection(raw).execute("SELECT id FROM employees").fetchall(), [])

    def test_context_manager_commits_on_success(self):
        raw = FakeRawConnection()
        with db.PostgresConnection(raw) as conn:
            conn.execute("SELECT 1")
        self.assertEqual(raw.commits, 1)
        self.assertEqual(raw.rollbacks, 0)
        self.assertTrue(raw.closed)

    def test_context_manager_rolls_back_on_error(self):
        raw = FakeRawConnection()
        with self.assertRaises(ValueError):
            with db.PostgresConnection(raw) as conn:
                conn.execute("SELECT 1")
                raise ValueError("boom")
        self.assertEqual(raw.rollbacks, 1)
        self.assertEqual(raw.commits, 0)
        self.assertTrue(raw.closed)

    def test_close_returns_connection_to_pool(self):
        pool = FakePool()
        conn = db.PostgresConnection(pool.getconn(), pool)
        conn.close()
        self.assertEqual(len(pool.returned), 1)

    def test_context_manager_returns_connection_to_pool(self):
        pool = FakePool()
        raw = pool.getconn()
        with db.PostgresConnection(raw, pool):
            pass
        self.assertEqual(pool.returned, [raw])


class BackendSelectionTests(unittest.TestCase):
    def test_sqlite_is_default_without_database_url(self):
        with patch.object(db, "DATABASE_URL", ""):
            self.assertFalse(db.using_postgres())

    def test_postgres_url_selects_postgres(self):
        for url in ("postgres://u:p@h:5432/d", "postgresql://u:p@h:5432/d"):
            with patch.object(db, "DATABASE_URL", url):
                self.assertTrue(db.using_postgres(), url)

    def test_non_postgres_url_falls_back_to_sqlite(self):
        with patch.object(db, "DATABASE_URL", "mysql://u:p@h/d"):
            self.assertFalse(db.using_postgres())


class RecordingOnlyConnection:
    """Captures emitted SQL without executing it, for dialect validation."""

    def __init__(self, seen, rows):
        self._seen = seen
        self._rows = rows

    def execute(self, sql, params=()):
        self._seen.append(sql)

        class _Cursor:
            def fetchone(_self):
                return self._rows[0] if self._rows else None

            def fetchall(_self):
                return list(self._rows)

        return _Cursor()

    def __enter__(self):
        return self

    def __exit__(self, *_exc):
        return False

    def commit(self):
        return None

    def rollback(self):
        return None

    def close(self):
        return None


@unittest.skipUnless(parse_sql is not None, "pglast is not installed")
class PostgresFaceStoreSqlTests(unittest.TestCase):
    def test_postgres_extra_schema_parses(self):
        with patch.object(db, "DATABASE_URL", PG_URL):
            statements = db._postgres_extra()
        self.assertTrue(statements, "face template tables must be created on PostgreSQL")
        for statement in statements:
            parse_as_postgres(statement)

    def test_face_template_tables_are_not_created_on_sqlite(self):
        with patch.object(db, "DATABASE_URL", ""):
            self.assertEqual(db._postgres_extra(), [])

    def test_postgres_face_store_emits_valid_sql(self):
        from backend.face_store import PostgresFaceStore

        seen = []
        rows = [{"label": 1, "data": b"blob", "c": 1, "v": 1}]

        def recording_get_conn():
            return RecordingOnlyConnection(seen, rows)

        store = PostgresFaceStore(probe_seconds=0.0)
        with patch.object(db, "get_conn", recording_get_conn):
            store.save(1, [b"a", b"b"])
            store.has(1)
            store.signature()
            list(store.iter_templates())
            store.clear(1)

        self.assertGreaterEqual(len(seen), 6)
        for sql in seen:
            parse_as_postgres(sql)

    def test_save_bumps_the_registry_version(self):
        from backend.face_store import PostgresFaceStore

        seen = []
        store = PostgresFaceStore()
        with patch.object(
            db, "get_conn", lambda: RecordingOnlyConnection(seen, [{"c": 0, "v": 0}])
        ):
            store.save(1, [b"a"])
        self.assertTrue(
            any("ON CONFLICT" in sql and "version" in sql for sql in seen),
            f"expected a version bump, saw {seen}",
        )

    def test_postgres_face_store_append_emits_valid_sql(self):
        from backend.face_store import PostgresFaceStore

        seen = []
        store = PostgresFaceStore()
        with patch.object(
            db, "get_conn", lambda: RecordingOnlyConnection(seen, [{"m": 4}])
        ):
            store.append(5, [b"a", b"b"])

        self.assertTrue(any("MAX(idx)" in sql for sql in seen), f"saw {seen}")
        self.assertEqual(sum("INSERT INTO face_templates" in sql for sql in seen), 2)
        self.assertTrue(any("ON CONFLICT" in sql for sql in seen), f"saw {seen}")
        for sql in seen:
            parse_as_postgres(sql)


class FaceStoreSelectionTests(unittest.TestCase):
    def test_sqlite_selects_the_file_store(self):
        from backend.face_store import FileFaceStore, PostgresFaceStore, build_store

        with patch.object(db, "DATABASE_URL", ""):
            self.assertIsInstance(build_store("/tmp/does-not-matter"), FileFaceStore)

    def test_postgres_selects_the_database_store(self):
        from backend.face_store import FileFaceStore, PostgresFaceStore, build_store

        with patch.object(db, "DATABASE_URL", PG_URL):
            self.assertIsInstance(build_store("/tmp/does-not-matter"), PostgresFaceStore)


class BackupAndPathTests(unittest.TestCase):
    def test_sqlite_backup_contains_the_database_file(self):
        import io
        import tarfile

        from backend import backup_sync

        with patch.object(db, "using_postgres", return_value=False):
            with tarfile.open(fileobj=io.BytesIO(backup_sync._archive_bytes())) as archive:
                self.assertIn("attendance.db", archive.getnames())

    def test_postgres_backup_contains_a_json_dump(self):
        import io
        import json
        import tarfile

        from backend import backup_sync

        snapshot = {"employees": [{"id": "EMP001"}], "face_templates": []}
        with patch.object(db, "using_postgres", return_value=True), patch.object(
            db, "export_snapshot", return_value=snapshot
        ):
            with tarfile.open(fileobj=io.BytesIO(backup_sync._archive_bytes())) as archive:
                names = archive.getnames()
                self.assertIn("attendance-data.json", names)
                self.assertNotIn("attendance.db", names)
                payload = json.loads(archive.extractfile("attendance-data.json").read())
        self.assertEqual(payload, snapshot)

    def test_binary_template_data_is_json_safe(self):
        self.assertEqual(db._jsonable(b"\x00\x01\xff"), "AAH/")

    def test_init_creates_missing_parent_directories(self):
        target = os.path.join(tempfile.mkdtemp(prefix="nested-db-"), "deep", "deeper", "a.db")
        with patch.object(db, "DB_PATH", target), patch.object(db, "DATABASE_URL", ""):
            db.init_db()
        self.assertTrue(os.path.exists(target))

    def test_postgres_snapshot_includes_face_tables(self):
        seen = []

        def recording_get_conn():
            return RecordingOnlyConnection(seen, [])

        with patch.object(db, "DATABASE_URL", PG_URL), patch.object(
            db, "get_conn", recording_get_conn
        ):
            snapshot = db.export_snapshot()
        self.assertIn("face_templates", snapshot)
        self.assertIn("face_registry", snapshot)
        self.assertIn("field_visits", snapshot)
        self.assertEqual(len(seen), 5)


if __name__ == "__main__":
    unittest.main()
